### ISSUE TITLE
Is there any room for baseBalanceSheet class?

### ISSUE THREAD

**Issue by zouhx11** [cogeorg/abm_template#3]
In banking system stress testing, it's very important to classify bank's balance sheet

**Comment by pafiedor** [comment]
Currently the balance sheet is classified through baseTransaction, so that each item on bank's balance sheet would consist of transactions of a given type (this being a template so the specific classes would need to be implemented in the actual non-abstract project, see https://github.com/cogeorg/blackrhino for examples).
Having said that, if you think another way of doing this would be better please do outline your idea a bit more on how you would structure this within abm_template and we'll take a closer look.
Best,
Paweł

**Comment by zouhx11** [comment]
Forgive me if I don't express my idea clearly, because my english isn't good.  I'm participating in Chinese Central Bank's stress testing program and write code for them. For now we don't have any transaction data between banks, only balance sheet and loan data(of course we only know classes, not counterparties). At this stage we just want to simulate fire sale module, which is given initial shock, some banks have to sell assets to meet regulation ratios, which causes asset price drop down and other banks' mark-to-market losses. In this case, I feel rather difficult to use blackrhino, although I like it. So I change to mesa and give each bank a balance sheet.

**Comment by zouhx11** [comment]
I know, with transaction based, It will be easy to make balance sheet "balanced", I will certainly borrow your ideas in blackrhino, really great works!

**Comment by pafiedor** [comment]
Your English is good, I just needed a bit of context. It’s clear now, I see what you mean.

I’ll need to think about whether it makes sense to amend something in the template or have a separate one for simulations based on restricted counterparty data/assumptions, I’ll be back on that.

What you can do, however, if you don’t care/know what the counterparties are is to create an agent type based on baseagent that’s going to be a representative counterparty and have all the balance sheet items of banks be transactions with the opposite side going to that representative counterparty. Then you assume no behaviour for that counterparty in the model and just concentrate on what happens with the banks. Hope that helps!

**Comment by zouhx11** [comment]
Thanks a lot, I will think about that. Before blackrhino I checked abce and its extension abecesl. These packages are written by Oxford guys and also used in Bank of England stress testing. I compared a abce and blackrhino, found that blackrhino's code is more readable and better organized. The only difference is they have an accounting module.

**Comment by pafiedor** [comment]
No worries, hope your project goes well. Feel free to fork abm_template & BlackRhino and customize for your project :) Thanks for the kind words.
